export enum Screens {
    HOME = "Home",
    WS_CR_INT = "WS_CR_INT",
    WS_CR_SUCCESS = "WS_CR_SUCCESS",
    WS_CR_FAIL = "WS_CR",
    WS_NAMING = "WS_Naming",
    WS_COM_INFO = "WS_COM_INFO",
    WS_CHECKIN_FORM = "WS_CHECKIN_FORM",
    WS_LOCATION = "WS_LOCATION",
    WS_TIME = "WS_TIME",
    EXAMPLE = "Example",
    HEADER = "Header",
    CHECKINQRSCAN = "CheckinQRScan",
    CHECKINVALIDATION = "CheckinValidation",
    CHECKOUTVALIDATION = "CheckoutValidation",
    WS_HOME = "WS_HOME",
    WS_CONFIG_SUCCESS = "WS_CONFIG_SUCCESS",
    LOG_IN = "Login",
    SIGN_IN = "Signin",
}
