const color = {
    BLACK: "#000",
    DARK: "#1D1617",
    WHITE: "#fff",
    GRAY_LIGHT: "#DDDADA",
    GRAY_MEDIUM: "#ADA4A5",
    GRAY_HEAVY: "#7B6F72",
    GRAY_BUTTON: "#F7F8F8",
    GRAY_BUTTON_CLICK: "#DCE0E0",
    BORDER: "#F7F8F8",
    BLUE_HEAVY: "#92A3FD",
    BLUE_LIGHT: "#9DCEFF",
    DARKEN_LIGHT: "#021475",
    PURLE_LIGHT: "#C58BF2",
    PURPLE_HEAVY: "#EEA4CE",
    BLUE_SHADOW: "#95ADFE4D",
    PURPLE_SHADOW: "#C58BF24D",
    WHITE_SHADOW: "#1D161712",
    TRANSPARENT: "transparent",
    RED_ERROR: "#CC0000",
};

export default color;
