import ILLUSTRATION from "../assets/images/illustration.png";
import ILLUSTRATION_2 from "../assets/images/illustration_2.png";
import ILLUSTRATION_3 from "../assets/images/illustration_3.png";
import LOCATION from "../assets/images/location.png";
import QR_CODE from "../assets/images/qr_code.png";
import USER_PHOTO from "../assets/images/user_photo.png";
import AVATAR from "../assets/images/avatar.png";
import CLOCK from "../assets/images/clock.png";
import BARCODE from "../assets/images/barCode.png";
export { ILLUSTRATION, ILLUSTRATION_2, ILLUSTRATION_3, LOCATION, QR_CODE, USER_PHOTO, AVATAR, CLOCK, BARCODE };
